### PR TITLE
1.19.3 Update

### PR DESCRIPTION
**Pull request by mvilk**
- Updated to 1.19.3 version (Doesn't work on previous versions) and closes issue [#33](https://github.com/adamviola/BoostedBrightness/issues/33)
- Updated dependencies
- Added issues page link to fabric.mod.json

### CODE REVIEW

**Comment by R00tB33rMan** [comment]
Mostly everything looks good; however, this PR will cause the options category in Sodium to crash your game. Likely just something missed/changed!

**Comment by Charles224488** [comment]
Hey @mvilk How do I change this to a jar file?

**Comment by Charles224488** [comment]
Thanks @mvilk, could you link a tutorial of how to change a zip file into a jar file? It would be really helpful.

**Comment by Charles224488** [comment]
Thanks @mvilk, this has helped alot!

**Comment by Charles224488** [comment]
Sorry this is not really related to PR, When I tried running 'start gradlew build' it just fails with the error Unsupported class file major version 63 in the boostedbrightness-master folder. Could you help me please?

**Comment by Charles224488** [comment]
@mvilk Do you have discord?

**Comment by adamviola** [comment]
Thanks for this! The mod is now officially updated to 1.19.3.

**Pull request closed without merging**
